# Generated by Django 4.2.5 on 2023-10-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btlgd', '0002_contact_remove_article_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Call',
        ),
    ]
